### ISSUE TITLE
need temporary home for additional books

### ISSUE THREAD

**Issue by infowetrust** [micahstubbs/books-map-prototypes#7]
Where should I add new books to be incorporated?
What format should the list be? Amazon wishlist? Doc of Amazon links or just ISBNs?

**Comment by micahstubbs** [comment]
@infowetrust good question.  let's make a new amazon wishlist, which we can then batch import.

**Comment by infowetrust** [comment]
I have created a new list: 📈 MORE DataViz Books at http://a.co/c6N1icB (and added some new books). Once these are processed in then we should move them on Amazon to the master list.
